image: gitpod/workspace-full

tasks:
  - name: Install Node.js v16.16.0
    command: nvm install 16.16.0

  - name: Switch to Node.js v16.16.0
    command: nvm use 16.16.0

  - name: Install NPM v8.11.0
    command: npm install -g npm@8.11.0

  - name: Run NPM install
    command: npm install

  - name: Start development server
    command: npm run serve